defmodule NavatrackWeb.Topics.NewTest do
  # import Phoenix.LiveViewTest
  use NavatrackWeb.ConnCase
  use NavatrackWeb.AuthCase
  # alias Navatrack.Works.Topic, as: X

  setup %{conn: conn} do
    {:ok, user} = my_user()
    {:ok, user} = my_sign_in(user)

    conn =
      conn
      |> Phoenix.ConnTest.init_test_session(%{})
      |> AshAuthentication.Plug.Helpers.store_in_session(user)

    {:ok, conn: conn}
  end

  test "new", %{conn: conn} do
    conn = get(conn, ~p"/topics/new")
    response = html_response(conn, 200)

    assert response =~ "Topics"

    assert response =~ "📛 Name"
    assert response =~ "🚦 Sign"
    assert response =~ "📍 Status"
    assert response =~ "🏷️ Tags"
    assert response =~ "🗒️ Note"

    assert response =~ "Contact"
    assert response =~ "🌐 Web"
    assert response =~ "📧 Email"
    assert response =~ "📱 Phone"
    assert response =~ "💬 Chat"
    assert response =~ "🗓️ Calendar"
    assert response =~ "📫 Postal"
    assert response =~ "🖇️ RDF Type"

    assert response =~ "Socials"
    assert response =~ "Bluesky URL"
    assert response =~ "Codeberg URL"
    assert response =~ "Facebook URL"
    assert response =~ "GitHub URL"
    assert response =~ "Instagram URL"
    assert response =~ "LinkedIn URL"
    assert response =~ "ORCID URL"
    assert response =~ "TikTok URL"
    assert response =~ "Wikipedia URL"
    assert response =~ "YouTube URL"

    assert response =~ "Location"
    assert response =~ "Country code (ISO 3166-1 Alpha 2)"
    assert response =~ "Subcountry code (ISO 3166-2)"
    assert response =~ "Postal code"
    assert response =~ "Latitude"
    assert response =~ "Longitude"
    assert response =~ "Chart"
    assert response =~ "URL"
    assert response =~ "TypeScript"

    assert response =~ "Images"
    assert response =~ "Avatar image 400x400"
    assert response =~ "Main image 1080x1080 square"
    assert response =~ "Main image 1920x1080 landscape"
    assert response =~ "Main image 1080x1920 portrait"

    assert response =~ "Ideals"
    assert response =~ "Purpose Statement"
    assert response =~ "Vision Statement"
    assert response =~ "Mission Statement"
    assert response =~ "Values Statement"

    assert response =~ "AI Agent Instructions"

    assert response =~ "Links"
    assert response =~ "🏠 Home"
    assert response =~ "🛎️ Concierge"
    assert response =~ "🎯 Target"
    assert response =~ "⚙️ Technical Contact"
    assert response =~ "🗓️ Calendar"
    assert response =~ "✨ AI"
    assert response =~ "💬 Chat"
    assert response =~ "📰 News"
    assert response =~ "📊 Charts"
    assert response =~ "🎥 Videos"
    assert response =~ "👷 Construction Worker"
    assert response =~ "🔮 Future"
    assert response =~ "🦋 Feature Tracker"
    assert response =~ "🐞 Bug Tracker"

    assert response =~ "Deeper Dive"
    assert response =~ "Glossary"
    assert response =~ "Email distribution list"
    assert response =~ "DaisyUI timeline HTML"
    assert response =~ "Org Mode"
    assert response =~ "Task list as markdown"
    assert response =~ "Ways Of Working"
    assert response =~ "Objectives and Key Results (OKRs)"
    assert response =~ "Key Performance Indicators (KPIs)"
    assert response =~ "Roles and Responsibilities"
    assert response =~ "Responsibility Assignment Matrix (RAM)"

    assert response =~ "Business Analysis"
    assert response =~ "GS1 Codes"
    assert response =~ "GS1 Digital Link"
    assert response =~ "GS1 Country Code"
    assert response =~ "GS1 Global Location Number"
    assert response =~ "International Standard Industrial Classification V4"
    assert response =~ "Code"
    assert response =~ "Name"
    assert response =~ "Six-Pager Double-Sider"
    assert response =~ "URL"
    assert response =~ "Text"

    assert response =~ "SWOT: Strengths Weaknesses Opportunities Threats"
    assert response =~ "Strengths"
    assert response =~ "Weaknesses"
    assert response =~ "Opportunities"
    assert response =~ "Threats"

    assert response =~ "STEEPLE: Social Technological Economic Environmental Political Legal Ethical"
    assert response =~ "Socials"
    assert response =~ "Technological"
    assert response =~ "Economic"
    assert response =~ "Environmental"
    assert response =~ "Political"
    assert response =~ "Legal"
    assert response =~ "Ethical"

    assert response =~ "Porter&#39;s Five Forces"
    assert response =~ "Threat Of Entrants"
    assert response =~ "Threat Of Substitutes"
    assert response =~ "Bargaining Power Of Customers"
    assert response =~ "Bargaining Power Of Suppliers"
    assert response =~ "Rivalry Of Competitors"

    assert response =~ "Policies"
    assert response =~ "Code of Conduct Policy"
    assert response =~ "Coordinated Disclosure Policy"
    assert response =~ "Copyright Policy"
    assert response =~ "Corrections Policy"
    assert response =~ "Diversity Policy"
    assert response =~ "Equal Opportunity Policy"
    assert response =~ "Ethics Policy"
    assert response =~ "Legal Policy"
    assert response =~ "License Policy"
    assert response =~ "Open Source Policy"
    assert response =~ "Privacy Policy"
    assert response =~ "Safety Policy"
    assert response =~ "Security Policy"
    assert response =~ "Socials Policy"
    assert response =~ "Staff Policy"

    assert response =~ "Arc42"
    assert response =~ "Arc42 section 01: Introduction and Goals"
    assert response =~ "Arc42 section 02: Constraints"
    assert response =~ "Arc42 section 03: Context and Scope"
    assert response =~ "Arc42 section 04: Solution Strategy"
    assert response =~ "Arc42 section 05: Building Block View"
    assert response =~ "Arc42 section 06: Runtime View"
    assert response =~ "Arc42 section 07: Deployment View"
    assert response =~ "Arc42 section 08: Crosscutting Concepts"
    assert response =~ "Arc42 section 09: Architectural Decisions"
    assert response =~ "Arc42 section 10: Quality Requirements"
    assert response =~ "Arc42 section 11: Risks and Technical Debt"
    assert response =~ "Arc42 section 12: Glossary"

    assert response =~ "Explain"
    assert response =~ "Explain Stakeholders"
    assert response =~ "Explain History"
    assert response =~ "Explain Authentication"
    assert response =~ "Explain Authorization"
    assert response =~ "Explain Use Cases"
    assert response =~ "Explain Demographics"
    assert response =~ "Explain UI"
    assert response =~ "Explain API"
    assert response =~ "Explain Data"
    assert response =~ "Explain Mobile"
    assert response =~ "Explain Legal"
    assert response =~ "Explain Financial"
    assert response =~ "Explain Service Level Agreement (SLA)"
    assert response =~ "Explain Disaster Recovery (DR)"

    assert response =~ "System Quality Attributes"
    assert response =~ "Availability"
    assert response =~ "Certifiability"
    assert response =~ "Compatibility"
    assert response =~ "Efficiency"
    assert response =~ "Governability"
    assert response =~ "Maintainability"
    assert response =~ "Observability"
    assert response =~ "Operability"
    assert response =~ "Recoverability"
    assert response =~ "Scalability"
    assert response =~ "Security"
    assert response =~ "Suitability"
    assert response =~ "Testability"
    assert response =~ "Transferability"
    assert response =~ "Translatability"
    assert response =~ "Warrantability"

    assert response =~ "Net Promoter Score"
    assert response =~ "Customer Perspective"
    assert response =~ "User Perspective"
    assert response =~ "Worker Perspective"
    assert response =~ "User Metrics"
    assert response =~ "Active Users"
    assert response =~ "Uptime Percentage"
    assert response =~ "Burn Rate"
    assert response =~ "Net Cash Per Week"
    assert response =~ "Hours Per Week"

    assert response =~ "Earned Value Management (EVM)"
    assert response =~ "Planned Value (PV)"
    assert response =~ "Earned Value (EV)"
    assert response =~ "Actual Cost (AC)"

    assert response =~ "Total Project Control (TPC)"
    assert response =~ "DIPP"
    assert response =~ "Progress Index (ratio)"
    assert response =~ "Progress Index (numerator)"
    assert response =~ "Progress Index (denominator)"
    assert response =~ "Expected Monetary Value"
    assert response =~ "Cost Estimate To Complete"

    assert response =~ "DORA Metrics"
    assert response =~ "Code Metrics"
    assert response =~ "Maintainability Index"
    assert response =~ "Line Count"
    assert response =~ "Test Automation Code Coverage"
    assert response =~ "Halstead Complexity Volume"
    assert response =~ "Halstead Complexity Difficulty"
    assert response =~ "Halstead Complexity Effort"
  end

end
