defmodule Navatrack.Works.Group.Fab do
  defmacro __using__(_opts) do
    quote do

        def fab!(map \\ %{}) do
        __MODULE__ |> Ash.Changeset.for_create(:create, __MODULE__.fab_map(map)) |> Ash.create!()
      end

      def fab_map(map \\ %{}) do
        Map.merge(
          %{
            locale_code: "en-US",
            parent_id: nil,
            parent_order: nil,
            ### card
            name: "my-name",
            sign: "○",
            status: "my-status",
            tagging: "my-tagging",
            note: "my-note",
            ### contact
            web: "https://my-web",
            email: "my-email@example.com",
            phone: "my-phone",
            chat: "my-chat",
            calendar: "my-calendar",
            postal: "my-postal",
            rdf_type: "my-rdf-type",
            ### social
            bluesky_as_url: "https://bsky.app/profile/my-handle",
            codeberg_as_url: "https://codeberg.org/in/my-handle",
            facebook_as_url: "https://facebook.com/my-handle",
            github_as_url: "https://github.com/in/my-handle",
            instagram_as_url: "https://instagram.com/my-handle",
            linkedin_as_url: "https://linkedin.com/in/my-handle",
            mastodon_as_url: "https://mastodon.social/@my-handle",
            orcid_as_url: "https://orcid.org/my-handle",
            tiktok_as_url: "https://tiktok.com/my-handle",
            wikipedia_as_url: "https://wikipedia.org/my-handle",
            youtube_as_url: "https://youtube.com/my-handle",
            ### location
            location_iso_3166_1_alpha_2: "my",
            location_iso_3166_2: "my-location-iso-3166-2",
            location_postal_code: "my-postal-code",
            location_latitude_as_decimal_degrees: "1.2",
            location_longitude_as_decimal_degrees: "3.4",
            ###
            daisyui_timeline_html: "my-daisyui-timeline-html",
            org_mode: "my-org-mode",
            task_list_as_markdown: "my-task-list-as-markdown",
            ways_of_working_as_markdown: "my-ways-of-working-as-markdown",
            objectives_and_key_results_as_markdown: "my-objectives-and-key-results-as-markdown",
            key_performance_indicators_as_markdown: "my-key-performance-indicators-as-markdown",
            ### images
            avatar_image_400x400_url: "https://my-avatar-image-400x400-url",
            avatar_image_400x400_alt: "my-avatar-image-400x400-alt",
            main_image_1080x1080_url: "https://my-main-image-1080x1080-url",
            main_image_1080x1080_alt: "my-main-image-1080x1080-alt",
            main_image_1920x1080_url: "https://my-main-image-1920x1080-url",
            main_image_1920x1080_alt: "my-main-image-1920x1080-alt",
            main_image_1080x1920_url: "https://my-main-image-1080x1920-url",
            main_image_1080x1920_alt: "my-main-image-1080x1920-alt",
            ### ideals
            purpose_statement: "my-purpose-statement",
            vision_statement: "my-vision-statement",
            mission_statement: "my-mission-statement",
            values_statement: "my-values-statement",
            ### ai
            ai_agent_instructions_as_url: "https://my-agent-instructions-as-url",
            ai_agent_instructions_as_markdown: "my-agent-instructions-as-markdown",
            ### emoji
            home_emoji_url: "https://my-home-emoji-url",
            bellhop_bell_emoji_url: "https://my-bellhop-bell-emoji-url",
            target_emoji_url: "https://my-target-emoji-url",
            gear_emoji_url: "https://my-gear-emoji-url",
            spiral_calendar_emoji_url: "https://my-spiral-calendar-emoji-url",
            sparkles_emoji_url: "https://my-sparkles-emoji-url",
            speech_bubble_emoji_url: "https://my-speech-bubble-emoji-url",
            newspaper_emoji_url: "https://my-newspaper-emoji-url",
            bar_chart_emoji_url: "https://my-bar-chart-emoji-url",
            movie_camera_emoji_url: "https://my-movie-camera-emoji-url",
            construction_worker_emoji_url: "https://my-construction-worker-emoji-url",
            crystal_ball_emoji_url: "https://my-crystal-ball-emoji-url",
            butterfly_emoji_url: "https://my-butterfly-emoji-url",
            lady_beetle_emoji_url: "https://my-lady-beetle-emoji-url",
            ### deeper dive
            email_distribution_list: "my-email-distribution-list",
            glossary_as_url: "https://my-glossary-as-url",
            glossary_as_markdown: "my-glossary-as-markdown",
            ### business analysis
            gs1_digital_link: "my-gs1-digital-link",
            gs1_country_code: "my-gs1-country-code",
            gs1_global_location_number: "my-gs1-global-location-number",
            isic_v4_code: "my-isic-v4-code",
            isic_v4_name: "my-isic-v4-name",
            six_pager_double_sider_as_url: "https://my-six_pager-double-sider-as-url",
            six_pager_double_sider_as_markdown: "my-six-pager-double-sider-as-markdown",
            ### swot
            swot_as_url: "https://my-swot-as-url",
            swot_strengths_as_markdown: "my-swot-strengths-as-markdown",
            swot_weaknesses_as_markdown: "my-swot-weaknesses-as-markdown",
            swot_opportunities_as_markdown: "my-swot-opportunities-as-markdown",
            swot_threats_as_markdown: "my-swot-opportunities-as-markdown",
            ### sipoc
            sipoc_as_url: "https://my-sipoc-as-url",
            sipoc_suppliers_as_markdown: "my-sipoc-suppliers-as-markdown",
            sipoc_inputs_as_markdown: "my-sipoc-inputs-as-markdown",
            sipoc_processes_as_markdown: "my-sipoc-processes-as-markdown",
            sipoc_outputs_as_markdown: "my-sipoc-outputs-as-markdown",
            sipoc_customers_as_markdown: "my-sipoc-customers-as-markdown",
            ### steeple
            steeple_as_url: "https://my-steeple-as-url",
            steeple_social_as_markdown: "my-steeple-social-as-markdown",
            steeple_technological_as_markdown: "my-steeple-technological-as-markdown",
            steeple_economic_as_markdown: "my-steeple-economic-as-markdown",
            steeple_environmental_as_markdown: "my-steeple-environmental-as-markdown",
            steeple_political_as_markdown: "my-steeple-political-as-markdown",
            steeple_legal_as_markdown: "my-steeple-legal-as-markdown",
            steeple_ethical_as_markdown: "my-steeple-ethical-as-markdown",
            roles_and_responsibilities_as_url: "https://my-roles-and-responsibilities-as-url",
            roles_and_responsibilities_as_markdown: "my-roles-and-responsibilities-as-markdown",
            responsibility_assignment_matrix_as_url: "https://my-responsibility-assignment-matrix-as-url",
            responsibility_assignment_matrix_as_markdown: "my-responsibility-assignment-matrix-as-markdown",
            ### porters five forces
            porters_five_forces_as_url: "https://my-porters-five-forces-as-url",
            porters_five_forces_entrants_as_markdown: "my-porters-five-forces-entrants-as-markdown",
            porters_five_forces_substitutes_as_markdown: "my-porters-five-forces-substitutes-as-markdown",
            porters_five_forces_customers_as_markdown: "my-porters-five-forces-customers-as-markdown",
            porters_five_forces_suppliers_as_markdown: "my-porters-five-forces-suppliers-as-markdown",
            porters_five_forces_competitors_as_markdown: "my-porters-five-forces-competitors-as-markdown",
            ### policy
            code_of_conduct_policy_as_url: "https://my-code-of-conduct-url",
            code_of_conduct_policy_as_markdown: "my-code-of-conduct-as-markdown",
            coordinated_disclosure_policy_as_url: "https://my-coordinated_disclosure-policy-as-url",
            coordinated_disclosure_policy_as_markdown: "my-coordinated_disclosure-policy-as-markdown",
            copyright_policy_as_url: "https://my-copyright-policy-as-url",
            copyright_policy_as_markdown: "my-copyright-policy-as-markdown",
            corrections_policy_as_url: "https://my-corrections-policy-as-url",
            corrections_policy_as_markdown: "my-corrections-policy-as-markdown",
            diversity_policy_as_url: "https://my-diversity-policy-as-url",
            diversity_policy_as_markdown: "my-diversity-policy-as-markdown",
            equal_opportunity_policy_as_url: "https://my-equal_opportunity-policy-as-url",
            equal_opportunity_policy_as_markdown: "my-equal_opportunity-policy-as-markdown",
            ethics_policy_as_url: "https://my-ethics-policy-as-url",
            ethics_policy_as_markdown: "my-ethics-policy-as-markdown",
            legal_policy_as_url: "https://my-legal-policy-as-url",
            legal_policy_as_markdown: "my-legal-policy-as-markdown",
            license_policy_as_url: "https://my-license-url",
            license_policy_as_markdown: "my-license-as-markdown",
            open_source_policy_as_url: "https://my-open_source-policy-as-url",
            open_source_policy_as_markdown: "my-open_source-policy-as-markdown",
            privacy_policy_as_url: "https://my-privacy-policy-as-url",
            privacy_policy_as_markdown: "my-privacy-policy-as-markdown",
            safety_policy_as_url: "https://my-safety-policy-as-url",
            safety_policy_as_markdown: "my-safety-policy-as-markdown",
            security_policy_as_url: "https://my-security-policy-as-url",
            security_policy_as_markdown: "my-security-policy-as-markdown",
            socials_policy_as_url: "https://my-socials-policy-as-url",
            socials_policy_as_markdown: "my-socials-policy-as-markdown",
            staff_policy_as_url: "https://my-staff-policy-as-url",
            staff_policy_as_markdown: "my-staff-policy-as-markdown",
            ### explain
            explain_stakeholders_as_markdown: "my-explain-stakeholders-as-markdown",
            explain_history_as_markdown: "my-explain-history-as-markdown",
            explain_authentication_as_markdown: "my-explain-authentication-as-markdown",
            explain_authorization_as_markdown: "my-explain-authorization-as-markdown",
            explain_use_cases_as_markdown: "my-explain-use-cases-as-markdown",
            explain_demographics_as_markdown: "my-explain-demographics-as-markdown",
            explain_ui_as_markdown: "my-explain-ui-as-markdown",
            explain_api_as_markdown: "my-explain-api-as-markdown",
            explain_data_as_markdown: "my-explain-data-as-markdown",
            explain_mobile_as_markdown: "my-explain-mobile-as-markdown",
            explain_legal_as_markdown: "my-explain-legal-as-markdown",
            explain_financial_as_markdown: "my-explain-financial-as-markdown",
            explain_service_level_agreement_as_markdown: "my-explain-service-level-agreement-as-markdown",
            explain_disaster_recovery_as_markdown: "my-explain-disaster-recovery-as-markdown",
            ### apache echart
            apache_echart_as_url: "https://my-apache-echart-as-url",
            apache_echart_as_typescript: "my-apache-echart-as-typescript",
            ### net promoter score
            net_promoter_score_customer_perspective_actual: 1.0,
            net_promoter_score_customer_perspective_expect: 2.0,
            net_promoter_score_customer_perspective_unit: "my-net_promoter-score-customer-perspective-unit",
            net_promoter_score_customer_perspective_description_as_markdown: "my-net_promoter-score-customer-perspective-description-as-markdown",
            net_promoter_score_user_perspective_actual: 1.0,
            net_promoter_score_user_perspective_expect: 2.0,
            net_promoter_score_user_perspective_unit: "my-net_promoter-score-user-perspective-unit",
            net_promoter_score_user_perspective_description_as_markdown: "my-net_promoter-score-user-perspective-description-as-markdown",
            net_promoter_score_worker_perspective_actual: 1.0,
            net_promoter_score_worker_perspective_expect: 2.0,
            net_promoter_score_worker_perspective_unit: "my-net_promoter-score-worker-perspective-unit",
            net_promoter_score_worker_perspective_description_as_markdown: "my-net_promoter_score-worker-perspective-description-as-markdown",
            ### active users
            active_users_actual: 1.0,
            active_users_expect: 2.0,
            active_users_unit: "my-active-users-unit",
            active_users_description: "my-active-users-description",
          },
          map
        )
      end

    end
  end
end
