defmodule Navatrack.Repo.Migrations.CreateInternationalStandardClassificationOfOccupations2008 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(
             :international_labor_organization_international_standard_classification_of_occupations2008s,
             primary_key: false
           ) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :code, :text
      add :title, :text
      add :definition, :text
    end
  end

  def down do
    drop table(
           :international_labor_organization_international_standard_classification_of_occupations2008s
         )
  end
end
