defmodule Navatrack.Repo.Migrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:products) do
      remove :net_promoter_score_value
      remove :six_pager_as_markdown
      remove :six_pager_as_url
    end
  end

  def down do
    alter table(:products) do
      add :six_pager_as_url, :text
      add :six_pager_as_markdown, :text
      add :net_promoter_score_value, :float
    end
  end
end
