defmodule Navatrack.Repo.Migrations.CreateOrganizations do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:organizations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :title, :text
      add :status, :text
      add :tags, {:array, :text}
      add :url, :text
      add :email, :text
      add :phone, :text
      add :messaging, :text
      add :postal, :text
      add :orcid_pid, :text
      add :rdf, :text
      add :linkedin_url, :text
      add :github_url, :text
      add :codeberg_url, :text
      add :location_iso_3166_1_alpha_2, :text
      add :location_iso_3166_2, :text
      add :location_postal_code, :text
      add :location_latitude_as_decimal_degrees, :decimal
      add :location_longitude_as_decimal_degrees, :decimal
      add :note, :text
      add :daisyui_timeline_html, :text
      add :org_mode, :text
      add :task_list_as_markdown, :text
      add :ways_of_working_as_markdown, :text
      add :objectives_and_key_results_as_markdown, :text
      add :key_performance_indicators_as_markdown, :text
      add :agents_as_markdown, :text
      add :avatar_400x400_url, :text
      add :avatar_400x400_alt, :text
      add :image_1080x1080_url, :text
      add :image_1080x1080_alt, :text
      add :image_1920x1080_url, :text
      add :image_1920x1080_alt, :text
      add :image_1080x1920_url, :text
      add :image_1080x1920_alt, :text
      add :gs1_digital_link, :text
      add :gs1_country_code, :text
      add :gs1_global_location_number, :text
      add :international_standard_industrial_classification_v4_code, :text
      add :international_standard_industrial_classification_v4_name, :text
      add :copyright_policy_as_url, :text
      add :copyright_policy_as_markdown, :text
      add :corrections_policy_as_url, :text
      add :corrections_policy_as_markdown, :text
      add :legal_policy_as_url, :text
      add :legal_policy_as_markdown, :text
      add :ethics_policy_as_url, :text
      add :ethics_policy_as_markdown, :text
      add :privacy_policy_as_url, :text
      add :privacy_policy_as_markdown, :text
      add :security_policy_as_url, :text
      add :security_policy_as_markdown, :text
      add :coordinated_disclosure_policy_as_url, :text
      add :coordinated_disclosure_policy_as_markdown, :text
      add :open_source_policy_as_url, :text
      add :open_source_policy_as_markdown, :text
      add :code_of_conduct_policy_as_url, :text
      add :code_of_conduct_policy_as_markdown, :text
      add :equal_opportunity_policy_as_url, :text
      add :equal_opportunity_policy_as_markdown, :text
      add :social_network_policy_as_url, :text
      add :social_network_policy_as_markdown, :text
      add :health_and_safety_policy_as_url, :text
      add :health_and_safety_policy_as_markdown, :text
      add :employee_handbook_policy_as_url, :text
      add :employee_handbook_policy_as_markdown, :text
      add :human_resources_policy_as_url, :text
      add :human_resources_policy_as_markdown, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    drop table(:organizations)
  end
end
