defmodule Navatrack.Repo.Migrations.CreateLuminaFoundationSkillLevel do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:lumina_foundation_skill_levels, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :number, :bigint
      add :title, :text
      add :description, :text
    end
  end

  def down do
    drop table(:lumina_foundation_skill_levels)
  end
end
