defmodule Navatrack.Repo.Migrations.CreateMessages do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:messages, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :sign, :text
      add :status, :text
      add :tagging, :text
      add :note, :text

      add :writer_id,
          references(:users,
            column: :id,
            name: "messages_writer_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :reader_id,
          references(:users,
            column: :id,
            name: "messages_reader_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:messages, "messages_writer_id_fkey")

    drop constraint(:messages, "messages_reader_id_fkey")

    drop table(:messages)
  end
end
