defmodule Navatrack.Repo.Migrations.CreateSkills do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:skills, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :title, :text
      add :status, :text
      add :tags, {:array, :text}
      add :summary_as_markdown, :text
      add :description_as_markdown, :text
      add :avatar_400x400_url, :text
      add :avatar_400x400_alt, :text
      add :image_1080x1080_url, :text
      add :image_1080x1080_alt, :text
      add :image_1920x1080_url, :text
      add :image_1920x1080_alt, :text
      add :image_1080x1920_url, :text
      add :image_1080x1920_alt, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    drop table(:skills)
  end
end
