defmodule Navatrack.Repo.Migrations.CreateUsers do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :title, :text
      add :status, :text
      add :tags, {:array, :text}
      add :url, :text
      add :phone, :text
      add :messaging, :text
      add :postal, :text
      add :orcid_pid, :text
      add :rdf, :text
      add :linkedin_url, :text
      add :github_url, :text
      add :codeberg_url, :text
      add :location_iso_3166_1_alpha_2, :text
      add :location_iso_3166_2, :text
      add :location_postal_code, :text
      add :location_latitude_as_decimal_degrees, :decimal
      add :location_longitude_as_decimal_degrees, :decimal
      add :note, :text
      add :daisyui_timeline_html, :text
      add :org_mode, :text
      add :task_list_as_markdown, :text
      add :ways_of_working_as_markdown, :text
      add :objectives_and_key_results_as_markdown, :text
      add :key_performance_indicators_as_markdown, :text
      add :agents_as_markdown, :text
      add :avatar_400x400_url, :text
      add :avatar_400x400_alt, :text
      add :image_1080x1080_url, :text
      add :image_1080x1080_alt, :text
      add :image_1920x1080_url, :text
      add :image_1920x1080_alt, :text
      add :image_1080x1920_url, :text
      add :image_1080x1920_alt, :text
      add :work_profile_resume_as_pdf_url, :text
      add :work_profile_resume_as_markdown, :text
      add :work_profile_curriculum_vitae_as_pdf_url, :text
      add :work_profile_curriculum_vitae_as_markdown, :text
      add :work_role_title, :text
      add :work_role_start_date, :date
      add :work_role_stop_date, :date
      add :work_role_level, :text
      add :work_role_description_as_markdown, :text
      add :work_role_professional_development_plan_markdown, :text
      add :work_role_onet_soc_2019_code, :text
      add :work_role_united_kingdom_civil_service_grade_abbreviation, :text
      add :work_role_united_kingdom_standard_occupational_classification_2020_code, :text

      add :work_role_united_kingdom_government_digital_and_data_profession_capability_framework_url,
          :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    alter table(:initiatives) do
      remove :net_promoter_score_value
      remove :six_pager_as_markdown
      remove :six_pager_as_url
    end
  end

  def down do
    alter table(:initiatives) do
      add :six_pager_as_url, :text
      add :six_pager_as_markdown, :text
      add :net_promoter_score_value, :float
    end

    alter table(:users) do
      remove :updated_at
      remove :inserted_at

      remove :work_role_united_kingdom_government_digital_and_data_profession_capability_framework_url

      remove :work_role_united_kingdom_standard_occupational_classification_2020_code
      remove :work_role_united_kingdom_civil_service_grade_abbreviation
      remove :work_role_onet_soc_2019_code
      remove :work_role_professional_development_plan_markdown
      remove :work_role_description_as_markdown
      remove :work_role_level
      remove :work_role_stop_date
      remove :work_role_start_date
      remove :work_role_title
      remove :work_profile_curriculum_vitae_as_markdown
      remove :work_profile_curriculum_vitae_as_pdf_url
      remove :work_profile_resume_as_markdown
      remove :work_profile_resume_as_pdf_url
      remove :image_1080x1920_alt
      remove :image_1080x1920_url
      remove :image_1920x1080_alt
      remove :image_1920x1080_url
      remove :image_1080x1080_alt
      remove :image_1080x1080_url
      remove :avatar_400x400_alt
      remove :avatar_400x400_url
      remove :agents_as_markdown
      remove :key_performance_indicators_as_markdown
      remove :objectives_and_key_results_as_markdown
      remove :ways_of_working_as_markdown
      remove :task_list_as_markdown
      remove :org_mode
      remove :daisyui_timeline_html
      remove :note
      remove :location_longitude_as_decimal_degrees
      remove :location_latitude_as_decimal_degrees
      remove :location_postal_code
      remove :location_iso_3166_2
      remove :location_iso_3166_1_alpha_2
      remove :codeberg_url
      remove :github_url
      remove :linkedin_url
      remove :rdf
      remove :orcid_pid
      remove :postal
      remove :messaging
      remove :phone
      remove :url
      remove :tags
      remove :status
      remove :title
    end
  end
end
