defmodule Navatrack.Repo.Migrations.Init do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:users, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :sign, :text

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :title, :text
      add :status, :text
      add :tags, {:array, :text}
      add :url, :text
      add :email, :text
      add :phone, :text
      add :messaging, :text
      add :postal, :text
      add :orcid_pid, :text
      add :rdf, :text
      add :linkedin_url, :text
      add :github_url, :text
      add :codeberg_url, :text
      add :location_iso_3166_1_alpha_2, :text
      add :location_iso_3166_2, :text
      add :location_postal_code, :text
      add :location_latitude_as_decimal_degrees, :decimal
      add :location_longitude_as_decimal_degrees, :decimal
      add :note, :text
      add :daisyui_timeline_html, :text
      add :org_mode, :text
      add :task_list_as_markdown, :text
      add :ways_of_working_as_markdown, :text
      add :objectives_and_key_results_as_markdown, :text
      add :key_performance_indicators_as_markdown, :text
      add :agents_as_markdown, :text
      add :avatar_400x400_url, :text
      add :avatar_400x400_alt, :text
      add :image_1080x1080_url, :text
      add :image_1080x1080_alt, :text
      add :image_1920x1080_url, :text
      add :image_1920x1080_alt, :text
      add :image_1080x1920_url, :text
      add :image_1080x1920_alt, :text
      add :work_profile_resume_as_pdf_url, :text
      add :work_profile_resume_as_markdown, :text
      add :work_profile_curriculum_vitae_as_pdf_url, :text
      add :work_profile_curriculum_vitae_as_markdown, :text
      add :work_role_title, :text
      add :work_role_start_date, :date
      add :work_role_stop_date, :date
      add :work_role_level, :text
      add :work_role_description_as_markdown, :text
      add :work_role_professional_development_plan_markdown, :text
      add :work_role_onet_soc_2019_code, :text
      add :work_role_united_kingdom_civil_service_grade_abbreviation, :text
      add :work_role_united_kingdom_standard_occupational_classification_2020_code, :text

      add :work_role_united_kingdom_government_digital_and_data_profession_capability_framework_url,
          :text
    end

    create unique_index(:users, [:email], name: "users_unique_email_index")

    create table(:tokens, primary_key: false) do
      add :jti, :text, null: false, primary_key: true
      add :subject, :text, null: false
      add :expires_at, :utc_datetime, null: false
      add :purpose, :text, null: false
      add :extra_data, :map

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:skills, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :sign, :text

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :title, :text
      add :status, :text
      add :tags, {:array, :text}
      add :summary_as_markdown, :text
      add :description_as_markdown, :text
      add :avatar_400x400_url, :text
      add :avatar_400x400_alt, :text
      add :image_1080x1080_url, :text
      add :image_1080x1080_alt, :text
      add :image_1920x1080_url, :text
      add :image_1920x1080_alt, :text
      add :image_1080x1920_url, :text
      add :image_1080x1920_alt, :text
    end

    create table(:organizations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :sign, :text

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :title, :text
      add :status, :text
      add :tags, {:array, :text}
      add :url, :text
      add :email, :text
      add :phone, :text
      add :messaging, :text
      add :postal, :text
      add :orcid_pid, :text
      add :rdf, :text
      add :linkedin_url, :text
      add :github_url, :text
      add :codeberg_url, :text
      add :location_iso_3166_1_alpha_2, :text
      add :location_iso_3166_2, :text
      add :location_postal_code, :text
      add :location_latitude_as_decimal_degrees, :decimal
      add :location_longitude_as_decimal_degrees, :decimal
      add :note, :text
      add :daisyui_timeline_html, :text
      add :org_mode, :text
      add :task_list_as_markdown, :text
      add :ways_of_working_as_markdown, :text
      add :objectives_and_key_results_as_markdown, :text
      add :key_performance_indicators_as_markdown, :text
      add :agents_as_markdown, :text
      add :avatar_400x400_url, :text
      add :avatar_400x400_alt, :text
      add :image_1080x1080_url, :text
      add :image_1080x1080_alt, :text
      add :image_1920x1080_url, :text
      add :image_1920x1080_alt, :text
      add :image_1080x1920_url, :text
      add :image_1080x1920_alt, :text
      add :gs1_digital_link, :text
      add :gs1_country_code, :text
      add :gs1_global_location_number, :text
      add :international_standard_industrial_classification_v4_code, :text
      add :international_standard_industrial_classification_v4_name, :text
      add :copyright_policy_as_url, :text
      add :copyright_policy_as_markdown, :text
      add :corrections_policy_as_url, :text
      add :corrections_policy_as_markdown, :text
      add :legal_policy_as_url, :text
      add :legal_policy_as_markdown, :text
      add :ethics_policy_as_url, :text
      add :ethics_policy_as_markdown, :text
      add :privacy_policy_as_url, :text
      add :privacy_policy_as_markdown, :text
      add :security_policy_as_url, :text
      add :security_policy_as_markdown, :text
      add :coordinated_disclosure_policy_as_url, :text
      add :coordinated_disclosure_policy_as_markdown, :text
      add :open_source_policy_as_url, :text
      add :open_source_policy_as_markdown, :text
      add :code_of_conduct_policy_as_url, :text
      add :code_of_conduct_policy_as_markdown, :text
      add :equal_opportunity_policy_as_url, :text
      add :equal_opportunity_policy_as_markdown, :text
      add :social_network_policy_as_url, :text
      add :social_network_policy_as_markdown, :text
      add :health_and_safety_policy_as_url, :text
      add :health_and_safety_policy_as_markdown, :text
      add :employee_handbook_policy_as_url, :text
      add :employee_handbook_policy_as_markdown, :text
      add :human_resources_policy_as_url, :text
      add :human_resources_policy_as_markdown, :text
    end

    create table(:lumina_foundation_skill_levels, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :sign, :text

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :number, :bigint
      add :title, :text
      add :description, :text
    end

    create table(
             :international_labor_organization_international_standard_classification_of_occupations2008s,
             primary_key: false
           ) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :code, :text
      add :title, :text
      add :definition, :text
    end

    create table(:initiatives, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :sign, :text

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :title, :text
      add :status, :text
      add :tags, {:array, :text}
      add :url, :text
      add :email, :text
      add :phone, :text
      add :messaging, :text
      add :postal, :text
      add :orcid, :text
      add :rdf, :text
      add :agents_as_url, :text
      add :agents_as_markdown, :text
      add :avatar_400x400_url, :text
      add :avatar_400x400_alt, :text
      add :splash_1080x1080_url, :text
      add :splash_1080x1080_alt, :text
      add :splash_1920x1080_url, :text
      add :splash_1920x1080_alt, :text
      add :splash_1080x1920_url, :text
      add :splash_1080x1920_alt, :text
      add :home_emoji_url, :text
      add :bellhop_bell_emoji_url, :text
      add :target_emoji_url, :text
      add :gear_emoji_url, :text
      add :spiral_calendar_emoji_url, :text
      add :sparkles_emoji_url, :text
      add :speech_bubble_emoji_url, :text
      add :newspaper_emoji_url, :text
      add :bar_chart_emoji_url, :text
      add :movie_camera_emoji_url, :text
      add :construction_worker_emoji_url, :text
      add :crystal_ball_emoji_url, :text
      add :butterfly_emoji_url, :text
      add :lady_beetle_emoji_url, :text
      add :note, :text
      add :email_distribution_list, :text
      add :daisyui_timeline_html, :text
      add :org_mode, :text
      add :task_list_as_markdown, :text
      add :ways_of_working_as_markdown, :text
      add :objectives_and_key_results_as_markdown, :text
      add :key_performance_indicators_as_markdown, :text
      add :glossary_as_url, :text
      add :glossary_as_markdown, :text
      add :six_pager_double_sider_as_url, :text
      add :six_pager_double_sider_as_markdown, :text
      add :swot_as_url, :text
      add :swot_as_markdown, :text
      add :porters_five_forces_as_url, :text
      add :porters_five_forces_as_markdown, :text
      add :pestle_as_url, :text
      add :pestle_as_markdown, :text
      add :roles_and_responsibilities_as_url, :text
      add :roles_and_responsibilities_as_markdown, :text
      add :responsibility_assignment_matrix_as_url, :text
      add :responsibility_assignment_matrix_as_markdown, :text
      add :code_of_conduct_url, :text
      add :code_of_conduct_as_markdown, :text
      add :license_url, :text
      add :license_as_markdown, :text
      add :arc42_as_url, :text
      add :arc42_as_markdown, :text
      add :arc42_01_introduction_and_goals_as_markdown, :text
      add :arc42_02_constraints_as_markdown, :text
      add :arc42_03_context_and_scope_as_markdown, :text
      add :arc42_04_solution_strategy_as_markdown, :text
      add :arc42_05_building_block_view_as_markdown, :text
      add :arc42_06_runtime_view_as_markdown, :text
      add :arc42_07_deployment_view_as_markdown, :text
      add :arc42_08_crosscutting_concepts_as_markdown, :text
      add :arc42_09_architectural_decisions_as_markdown, :text
      add :arc42_10_quality_requirements_as_markdown, :text
      add :arc42_11_risks_and_technical_debt_as_markdown, :text
      add :arc42_12_glossary_as_markdown, :text
      add :explain_stakeholders_as_markdown, :text
      add :explain_history_as_markdown, :text
      add :explain_authentication_as_markdown, :text
      add :explain_authorization_as_markdown, :text
      add :explain_use_cases_as_markdown, :text
      add :explain_demographics_as_markdown, :text
      add :explain_ui_as_markdown, :text
      add :explain_api_as_markdown, :text
      add :explain_data_as_markdown, :text
      add :explain_mobile_as_markdown, :text
      add :explain_legal_as_markdown, :text
      add :explain_financial_as_markdown, :text
      add :explain_service_level_agreement_as_markdown, :text
      add :explain_disaster_recovery_as_markdown, :text
      add :quality_availability_as_markdown, :text
      add :quality_certifiability_as_markdown, :text
      add :quality_compatibility_as_markdown, :text
      add :quality_efficiency_as_markdown, :text
      add :quality_governability_as_markdown, :text
      add :quality_maintainability_as_markdown, :text
      add :quality_observability_as_markdown, :text
      add :quality_operability_as_markdown, :text
      add :quality_recoverability_as_markdown, :text
      add :quality_scalability_as_markdown, :text
      add :quality_security_as_markdown, :text
      add :quality_suitability_as_markdown, :text
      add :quality_testability_as_markdown, :text
      add :quality_transferability_as_markdown, :text
      add :quality_translatability_as_markdown, :text
      add :quality_warrantability_as_markdown, :text
      add :apache_echart_as_url, :text
      add :apache_echart_as_typescript, :text
      add :net_promoter_score_actual_value, :float
      add :net_promoter_score_target_value, :float
      add :net_promoter_score_unit, :text
      add :net_promoter_score_description_as_markdown, :text
      add :active_users_actual_value, :bigint
      add :active_users_target_value, :bigint
      add :active_users_unit, :text
      add :active_users_description, :text
      add :uptime_percentage_actual_value, :float
      add :uptime_percentage_target_value, :float
      add :uptime_percentage_unit, :text
      add :uptime_percentage_description, :text
      add :burn_rate_net_cash_per_week_actual_value, :bigint
      add :burn_rate_net_cash_per_week_target_value, :bigint
      add :burn_rate_net_cash_per_week_unit, :text
      add :burn_rate_net_cash_per_week_description, :text
      add :burn_rate_hours_per_week_actual_value, :bigint
      add :burn_rate_hours_per_week_target_value, :bigint
      add :burn_rate_hours_per_week_unit, :text
      add :burn_rate_hours_per_week_description, :text
      add :total_project_control_dipp, :float
      add :total_project_control_dipp_progress_index_ratio, :float
      add :total_project_control_dipp_progress_index_numerator, :float
      add :total_project_control_dipp_progress_index_denominator, :float
      add :total_project_control_expected_monetary_value, :float
      add :total_project_control_cost_estimate_to_complete, :float
      add :deployment_frequency_actual_value, :float
      add :deployment_frequency_target_value, :float
      add :deployment_frequency_unit, :text
      add :deployment_frequency_description, :text
      add :lead_time_for_changes_actual_value, :float
      add :lead_time_for_changes_target_value, :float
      add :lead_time_for_changes_unit, :text
      add :lead_time_for_changes_description, :text
      add :change_failure_rate_actual_value, :float
      add :change_failure_rate_target_value, :float
      add :change_failure_rate_unit, :text
      add :change_failure_rate_description, :text
      add :mean_time_to_recovery_actual_value, :float
      add :mean_time_to_recovery_target_value, :float
      add :mean_time_to_recovery_unit, :text
      add :mean_time_to_recovery_description, :text
      add :maintainability_index_actual_value, :float
      add :maintainability_index_target_value, :float
      add :maintainability_index_unit, :text
      add :maintainability_index_description, :text
      add :line_count_actual_value, :float
      add :line_count_target_value, :float
      add :line_count_unit, :text
      add :line_count_description, :text
      add :test_automation_code_coverage_actual_value, :float
      add :test_automation_code_coverage_target_value, :float
      add :test_automation_code_coverage_unit, :text
      add :test_automation_code_coverage_description, :text
      add :halstead_complexity_volume_actual_value, :float
      add :halstead_complexity_volume_target_value, :float
      add :halstead_complexity_volume_unit, :text
      add :halstead_complexity_volume_description, :text
      add :halstead_complexity_difficulty_actual_value, :float
      add :halstead_complexity_difficulty_target_value, :float
      add :halstead_complexity_difficulty_unit, :text
      add :halstead_complexity_difficulty_description, :text
      add :halstead_complexity_effort_actual_value, :float
      add :halstead_complexity_effort_target_value, :float
      add :halstead_complexity_effort_unit, :text
      add :halstead_complexity_effort_description, :text
    end
  end

  def down do
    drop table(:initiatives)

    drop table(
           :international_labor_organization_international_standard_classification_of_occupations2008s
         )

    drop table(:lumina_foundation_skill_levels)

    drop table(:organizations)

    drop table(:skills)

    drop table(:tokens)

    drop_if_exists unique_index(:users, [:email], name: "users_unique_email_index")

    drop table(:users)
  end
end
