classDiagram
    class IloIsco2008 {
        UUID id
        String locale_code
        String code
        String name
        String definition
        read()
    }
    class LuminaFoundationSkillLevel {
        UUID id
        String locale_code
        Integer number
        String name
        String description
        read()
    }
    class UkGdadPcfRole {
        UUID id
        String locale_code
        String family
        String name
        String url
        String description_as_markdown
        String level_name
        String level_description_as_markdown
        Boolean senior_civil_service_flag
        read()
    }
    class UkGdadPcfSkill {
        UUID id
        String locale_code
        String name
        String url
        String description_as_markdown
        String level_1_description_as_markdown
        String level_2_description_as_markdown
        String level_3_description_as_markdown
        String level_4_description_as_markdown
        String roles_that_require_this_trait_as_markdown
        read()
    }


