classDiagram
    class Topic {
        UUID id
        destroy()
        update(UtcDatetimeUsec created_at, UtcDatetimeUsec updated_at, UtcDatetimeUsec deleted_at, String sign, ...)
        read()
        create(UtcDatetimeUsec created_at, UtcDatetimeUsec updated_at, UtcDatetimeUsec deleted_at, String sign, ...)
    }
    class Trait {
        UUID id
        destroy()
        update(UtcDatetimeUsec created_at, UtcDatetimeUsec updated_at, UtcDatetimeUsec deleted_at, String sign, ...)
        read()
        create(UtcDatetimeUsec created_at, UtcDatetimeUsec updated_at, UtcDatetimeUsec deleted_at, String sign, ...)
    }


