classDiagram
    class Initiative {
        UUID id
        destroy()
        update(UtcDatetimeUsec created_at, UtcDatetimeUsec updated_at, UtcDatetimeUsec deleted_at, String sign, ...)
        read()
        create(UtcDatetimeUsec created_at, UtcDatetimeUsec updated_at, UtcDatetimeUsec deleted_at, String sign, ...)
    }
    class Skill {
        UUID id
        destroy()
        update(UtcDatetimeUsec created_at, UtcDatetimeUsec updated_at, UtcDatetimeUsec deleted_at, String sign, ...)
        read()
        create(UtcDatetimeUsec created_at, UtcDatetimeUsec updated_at, UtcDatetimeUsec deleted_at, String sign, ...)
    }


